# Generated by Django 5.2.5 on 2025-08-21 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='object_type',
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='award',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseworks', to='portfolio.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseworks', to='portfolio.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseworks', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='portfolio.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='file',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='portfolio.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='portfolio.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='knowledgeexchange',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_exchanges', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiads', to='portfolio.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiads_prepared', to='portfolio.teacher', verbose_name='Подготовивший педагог'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portfolio.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='portfolio.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='portfolio.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teachingload',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='portfolio.teacher', verbose_name='Педагог'),
        ),
        migrations.AddIndex(
            model_name='award',
            index=models.Index(fields=['teacher_id', 'level'], name='awards_teacher_7b94fe_idx'),
        ),
        migrations.AddIndex(
            model_name='coursework',
            index=models.Index(fields=['teacher_id', 'discipline_id'], name='courseworks_teacher_a0f058_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['supervisor_id'], name='diplomas_supervi_701af0_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['teacher_id'], name='education_teacher_67e856_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['teacher_id', 'start_date', 'end_date'], name='experience_teacher_42645d_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['content_type', 'object_id'], name='files_content_54cb22_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student_id', 'discipline_id', 'teacher_id'], name='grades_student_de0e76_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeexchange',
            index=models.Index(fields=['teacher_id', 'event_date'], name='knowledge_e_teacher_dbaeec_idx'),
        ),
        migrations.AddIndex(
            model_name='olympiad',
            index=models.Index(fields=['teacher_id', 'level'], name='olympiads_teacher_4311d5_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['teacher_id'], name='publication_teacher_55af21_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['teacher_id'], name='qualificati_teacher_600762_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group_id'], name='students_group_i_234511_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_name', 'first_name'], name='teachers_last_na_0e6b74_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingload',
            index=models.Index(fields=['teacher_id', 'discipline_id', 'group_id'], name='teaching_lo_teacher_435b98_idx'),
        ),
    ]
