# Generated by Django 5.2.5 on 2025-08-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_teacher_photo'),
        ('portfolio', '0005_auto_20250823_1544'),
    ]

    operations = [
    ]
