# Generated by Django 5.2.5 on 2025-08-23 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0007_create_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExperience',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=101)),
                ('general_experience', models.FloatField(null=True)),
                ('education_experience', models.FloatField(null=True)),
                ('college_experience', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Опыт педагога',
                'verbose_name_plural': 'Опыт педагогов',
                'db_table': 'teacher_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherPortfolio',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=101)),
                ('education_count', models.IntegerField(null=True)),
                ('general_experience_years', models.FloatField(null=True)),
                ('taught_disciplines', models.TextField(null=True)),
                ('student_average_grade', models.FloatField(null=True)),
                ('diploma_count', models.IntegerField(null=True)),
                ('publication_count', models.IntegerField(null=True)),
                ('award_count', models.IntegerField(null=True)),
                ('winner_count', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Портфолио педагога',
                'verbose_name_plural': 'Портфолио педагогов',
                'db_table': 'teacher_portfolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingQuality',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=101)),
                ('discipline', models.CharField(max_length=255)),
                ('group_number', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('average_grade', models.FloatField(null=True)),
                ('grade_count', models.IntegerField()),
                ('percent_excellent', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Качество обучения',
                'verbose_name_plural': 'Качество обучения',
                'db_table': 'teaching_quality',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='file',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
