# Generated by Django 5.2.5 on 2025-08-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_teacherexperience_teacherportfolio_teachingquality_and_more'),
        ('portfolio', '0009_auto_20250823_1646'),
    ]

    operations = [
    ]
