# Generated by Django 5.2.5 on 2025-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0010_merge_20250823_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Размер'),
        ),
    ]
