# Generated by Django 5.2.5 on 2025-08-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_file_file_path_alter_file_file_size_and_more'), 
    ]

    operations = [
        # Проверяем и добавляем files_file_size_check, если его нет
        migrations.RunSQL(
            sql=[
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'files_file_size_check'
                    ) THEN
                        ALTER TABLE files ADD CONSTRAINT files_file_size_check CHECK (file_size > 0);
                    END IF;
                END
                $$;
                """
            ],
            reverse_sql=migrations.RunSQL.noop  # Откат миграции не предусмотрен
        ),
        # Проверяем и добавляем files_file_type_check, если его нет
        migrations.RunSQL(
            sql=[
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'files_file_type_check'
                    ) THEN
                        ALTER TABLE files ADD CONSTRAINT files_file_type_check CHECK (file_type IN ('PDF', 'JPG', 'JPEG', 'PNG', 'DOC', 'DOCX'));
                    END IF;
                END
                $$;
                """
            ],
            reverse_sql=migrations.RunSQL.noop
        ),
        # Проверяем и добавляем files_object_id_95b6785b_check, если его нет
        migrations.RunSQL(
            sql=[
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'files_object_id_95b6785b_check'
                    ) THEN
                        ALTER TABLE files ADD CONSTRAINT files_object_id_95b6785b_check CHECK (object_id >= 0);
                    END IF;
                END
                $$;
                """
            ],
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
